name: CI
on:
  push: { branches: [ main ] }
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: { go-version: '1.19' }
      - uses: golangci/golangci-lint-action@v3
        with: { version: "v1.49", args: "--timeout 5m ./..." }

  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: { go-version: '1.19' }
      - run: docker compose up -d
        working-directory: example
      - name: Wait for keycloak
        run: curl --head -X HEAD --retry 60 --retry-all-errors --retry-delay 10 http://localhost:8081
      - name: Wait for authelia
        run: curl --head -X GET --retry 60 --retry-all-errors --retry-delay 10 http://localhost:8082
      - name: Test
        run: go test ./...